os: linux
language: go
go: "1.15.5"
go_import_path: github.com/prymitive/kthxbye
env:
  - GO111MODULE=on

jobs:
  include:
    - stage: Build and Deploy
      name: Cross compile binaries
      if: (repo = prymitive/kthxbye AND type != pull_request) OR (fork = true AND type = pull_request)
      cache:
        directories:
          # https://restic.net/blog/2018-09-02/travis-build-cache
          - $HOME/.cache/go-build
          - $HOME/gopath/pkg/mod
      before_cache:
        # this log file is updated on every get/set operation
        # so it forces new cache archive on every build
        # remove it before creating cache archive
        - rm -vf $HOME/.cache/go-build/log.txt
      script:
        # prune GOCACHE if it gets too big
        - ./scripts/prune-go-cache.sh
        - export SOURCE_DATE_EPOCH=$(git show -s --format=%ci ${TRAVIS_TAG:-${TRAVIS_COMMIT}}^{commit})
        - travis_retry make crosscompile -j 2
        - for i in kthxbye-*; do tar --mtime="${SOURCE_DATE_EPOCH}" --owner=0 --group=0 --numeric-owner -c $i | gzip -n - > $i.tar.gz; done
        - shasum -a 512 kthxbye-*.tar.gz | tee sha512sum.txt
        # verify that there are no uncommited changes
        - git diff --exit-code
        # print GOCACHE size
        - ./scripts/prune-go-cache.sh --dry-run
      deploy:
        provider: releases
        api_key:
          secure: lq3GGzGOgaGq4n8P1x9rHTXfok1GC2zqcEJDpXoq7vKW/bhLD0ecCEH1QirbNACw1Do8PD4KC2S0uC0E1wry5zJseM4rFzsSM6gsSmIqZlMGjx+94jOqAxuPaL2e/q6yPu+0oWZUapzXl5S8tJUnkKdBjnMfX/6ZrLXyqI+igLQzmX55/kjih5fY76mf5XmEr2YsO493LGSVUjgu/RglsrsJ52qHq+7dzs00Mru9vUkAm+N6TdBte0tc3bhaqbHspt9XMxcba9xGXY8uGatSWNiYIPsm4YXlzZXt6++DvPNYdOcZWc8rOfeaxSTIEvYk25lN9helF2DlbB3kpayVaNqVaHODFn5q4jz+/OU0Tix4sC1mjlmcNM9lqeR9c083yGwUvfhVzFSpWgQEJvIWcfB6zUeGkffu4L8/3HZiNoeTFnePB6zQmFdX42jvQmxsbEzoYr6X68F7djHrBuUbuUJFN1e+AQbI8o0rJAJj+xjUEngEWTYKxKoM9nctauViMZXnCjrIv8q29a5g7W9lhIKB+I4onwTNSE6g1OpCk8EIkYqR200ac0HKyKoz0tEF/jKUa0l9tFNxLgVBZ8ZWPmDRQr7APMdnnrlefnpy5Ty1ADX1bw36yr66kGKb27uGFEdxqhD9kCkCewTC6jzkkR/Gz8CF7O/M54ARlBG09xc=
        skip_cleanup: true
        file_glob: true
        file:
          - kthxbye-*.tar.gz
          - sha512sum.txt
        on:
          repo: prymitive/kthxbye
          tags: true
