name: Build Go binary

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-mod-

      - name: Cache Go build cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-cache-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-cache-

      - name: Check out code
        uses: actions/checkout@v2

      - name: Extract git tag
        id: git_ref
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}

      - name: Crosscompile binaries
        run: make crosscompile -j 2

      - name: Compress binaries
        if: startsWith(github.ref, '/refs/tags/v.+')
        run: |
          mkdir -p artifacts
          export SOURCE_DATE_EPOCH=$(git show -s --format=%ci ${{ steps.git_ref.outputs.TAG }}^${GITHUB_SHA})
          for i in kthxbye-*; do tar --mtime="${SOURCE_DATE_EPOCH}" --owner=0 --group=0 --numeric-owner -c $i | gzip -n - > artifacts/$i.tar.gz; done
          shasum -a 512 kthxbye-*.tar.gz | tee artifacts/sha512sum.txt

      - name: Upload binaries to GitHub release
        if: startsWith(github.ref, '/refs/tags/v.+')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/*
          file_glob: true
          tag: ${{ steps.git_ref.outputs.TAG }}
          overwrite: true
