name: Docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: lmierzwa/kthxbye
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag ${DOCKER_IMAGE}:latest

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Extract git tag
        if: github.event_name == 'release'
        id: git_ref
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}

      - name: Tag Docker image
        if: github.event_name == 'release'
        run: docker tag ${DOCKER_IMAGE}:latest ${DOCKER_IMAGE}:${{ steps.git_ref.outputs.TAG }}

      - name: Login to Docker Hub
        if: github.event_name == 'release'
        shell: bash
        run: echo "${DOCKER_HUB_PASSWORD}" | docker login -u lmierzwa --password-stdin
        env:
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push Docker image
        if: github.event_name == 'release'
        run: docker push ${DOCKER_IMAGE}
