name: Verify go.sum

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tidy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.5

      - name: Cache Go modules and build cache
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Check out code
        uses: actions/checkout@v2

      - name: Go mod tidy
        run: go mod tidy

      - name: Check for local changes
        run: git diff --exit-code
