name: Verify go.sum

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tidy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.2

      - name: Check out code
        uses: actions/checkout@v2

      - name: Go mod tidy
        run: |
          go mod tidy
          cd tools/golangci-lint && go mod tidy

      - name: Check for local changes
        run: git diff --exit-code
